name: Weekly Link Check

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Print every URL status'
        required: false
        default: 'true'
  schedule:
    - cron: '0 9 * * 1' # Mondays 09:00 UTC

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run link checker
        env:
          PYTHONUNBUFFERED: "1"   # ensure live logs
        run: |
          python -u check_links.py \
            --input data/urls.xlsx \
            --output reports/link_report_shard${{ matrix.shard }}.csv \
            --output-xlsx "" \
            --shard-index ${{ matrix.shard }} \
            --shard-count 4 \
            --concurrency 100 \
            $([ "${{ github.event.inputs.verbose }}" = "true" ] && echo --verbose)

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: link-reports
          path: reports/*.csv

  combine:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: link-reports
          path: reports

      # Merge shard CSVs without heredocs or extra Python
      - name: Merge CSVs and commit
        shell: bash
        run: |
          shopt -s nullglob
          files=(reports/link_report_shard*.csv)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No shard CSVs found; nothing to merge."
            exit 0
          fi

          # Keep header from first file, then append bodies from all
          { head -n 1 "${files[0]}"; for f in "${files[@]}"; do tail -n +2 "$f"; done; } > reports/link_report.csv
          echo "Merged ${#files[@]} shards into reports/link_report.csv"

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add reports/link_report.csv
          git commit -m "Update link report [skip ci]" || echo "No changes to commit"
          git push
